name: CI

on:
  pull_request:
    branches: [main]

jobs:
  run-test:
    name: 'Run tests'
    runs-on: ubuntu-latest

    steps:
      - name: Git clone
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest
        env:
          CI_RUN: true
          PYTHONDONTWRITEBYTECODE: 1
          PYTHONUNBUFFERED: 1